const fs = require('fs');

const content = fs.readFileSync('./src/data/mapData.ts', 'utf-8');
const idRegex = /(?:sub|cat)\('([^']+)',\s*'([^']+)'/g;
let match;
const nodes = [];
while ((match = idRegex.exec(content)) !== null) {
  nodes.push({ id: match[1], label: match[2] });
}

const getDetailedText = (id, label) => {
  let w_it = "", w_en = "", u_it = "", u_en = "";
  
  if (id.includes('endpoint-hygiene')) {
    w_it = "Pratica di sicurezza focalizzata sul mantenimento dello stato di conformità e pulizia dei dispositivi finali (PC, server, mobile). Include configurazioni sicure, patching e rimozione di software non autorizzato. Garantisce l'integrità del dispositivo.";
    u_it = "Impedisce agli attaccanti di sfruttare vulnerabilità note e malconfigurazioni basilari, abbattendo drasticamente la superficie d'attacco a livello di dispositivo utente aziendale.";
    w_en = "Security practice focused on maintaining the compliance and cleanliness of end-user devices (PCs, servers, mobile). It includes secure configurations, patching, and the removal of unauthorized software to ensure device integrity.";
    u_en = "Prevents attackers from exploiting known vulnerabilities and basic misconfigurations, drastically reducing the attack surface at the corporate user device level.";
  } else if (id.includes('edr-xdr')) {
    w_it = "Tecnologie avanzate (Endpoint/Extended Detection and Response) che aggregano telemetria dai dispositivi e dalla rete. Utilizzano analisi comportamentale, firme Cloud e AI per individuare minacce in esecuzione anomale.";
    u_it = "Fondamentale per identificare, tracciare e neutralizzare attacchi complessi (come malware fileless o operatori ransomware) in tempo reale, isolando rapidamente gli host compromessi.";
    w_en = "Advanced technologies (Endpoint/Extended Detection and Response) converging telemetry from devices and networks. They utilize behavioral analysis, Cloud signatures, and AI to identify anomalous executing threats.";
    u_en = "Crucial for identifying, tracking, and neutralizing complex attacks (such as fileless malware or ransomware operators) in real time by rapidly isolating compromised hosts.";
  } else if (id.includes('mdm')) {
    w_it = "Soluzione aziendale (Mobile Device Management) per gestire, monitorare e proteggere centralmente dispositivi mobili (smartphone, tablet) e laptop in roaming.";
    u_it = "Consente di applicare policy crittografiche obbligatorie, cancellare dati da remoto (remote wipe) in caso di furto e separare il traffico aziendale da quello personale (containerizzazione).";
    w_en = "Enterprise solution (Mobile Device Management) for centrally managing, monitoring, and securing roaming mobile devices (smartphones, tablets) and laptops.";
    u_en = "Allows enforcement of mandatory cryptographic policies, remote data wiping in case of theft, and isolation of corporate traffic from personal data (containerization).";
  } else if (id.includes('ngav')) {
    w_it = "Evoluzione degli antivirus tradizionali. Anziché basarsi su firme note statiche, l'NGAV analizza il comportamento dei processi in memoria e usa il machine learning locale/cloud per inferenze di pericolosità.";
    u_it = "Blocca istantaneamente attacchi zero-day, script dannosi in PowerShell ed exploit moderni che eludono l'analisi statica dei sistemi legacy.";
    w_en = "Evolution of traditional antiviruses. Instead of relying on static known signatures, NGAV analyzes memory process behavior and uses local/cloud machine learning for threat inference.";
    u_en = "Instantly blocks zero-day attacks, malicious PowerShell scripts, and modern exploits that easily bypass legacy static analysis systems.";
  } else if (id.includes('dlp') || id.includes('data-leakage')) {
    w_it = "Sistemi e processi (Data Leakage Prevention) progettati per rilevare, monitorare e prevenire la trasmissione non autorizzata di informazioni sensibili all'esterno del perimetro logico aziendale o cloud.";
    u_it = "Protegge la proprietà intellettuale e i dati regolamentati (es. GDPR), bloccando proattivamente email non autorizzate, upload web o trasferimenti USB di file classificati.";
    w_en = "Systems and processes (Data Leakage Prevention) designed to detect, monitor, and prevent the unauthorized transmission of sensitive information outside the logical corporate or cloud perimeter.";
    u_en = "Protects intellectual property and regulated data (e.g., GDPR), proactively blocking unauthorized emails, web uploads, or USB transfers of classified files.";
  } else if (id.includes('data-classification')) {
    w_it = "Insieme di processi metodologici o automatizzati per l'identificazione, l'organizzazione e l'etichettatura dei dati in base a precisi livelli di sensibilità (es. Pubblico, Interno, Confidenziale).";
    u_it = "Costituisce il layer fondazionale per applicare controlli di sicurezza (crittografia, DLP, access control) proporzionati solo dove strettamente necessari, garantendo compliance e abbattendo i costi.";
    w_en = "Methodological or automated processes for identifying, organizing, and labeling data based on precise levels of sensitivity (e.g., Public, Internal, Confidential).";
    u_en = "Forms the foundational layer to apply proportional security controls (encryption, DLP, access control) only where strictly necessary, ensuring compliance and cutting costs.";
  } else if (id.includes('data-retention')) {
    w_it = "Politiche direttive e tecniche operative che stabiliscono il ciclo di vita delle informazioni: per quanto tempo conservare i dati per motivi aziendali o legali, e i requisiti precisi per la loro distruzione criptografica.";
    u_it = "Diminuisce drasticamente le responsabilità dell'organizzazione (liability): eliminare permanentemente i dati superflui significa annullare i danni in caso di potenziale data breach futuro.";
    w_en = "Directive policies and operational techniques establishing the information lifecycle: how long to retain data for business or legal reasons, and precise requirements for its cryptographic destruction.";
    u_en = "Drastically decreases organizational liability: permanently deleting superfluous data equates to nullifying potential damages in case of a future data breach.";
  } else if (id.includes('container-sec')) {
    w_it = "Approccio olografico per mettere in sicurezza i cluster Kubernetes e motori Docker o cri-o. Comprende l'analisi statica delle immagini, la segmentazione di rete del network namespace e la sicurezza runtime del nodo host (come l'abuso di SYS_ADMIN).";
    u_it = "Impedisce la temuta 'container escape' (intrusione nel sistema host aziendale) e previene malconfigurazioni o l'uso malevolo delle risorse cloud per cryptomining.";
    w_en = "Holistic approach to securing Kubernetes clusters and Docker/cri-o engines. Includes static analysis of images, network namespace segmentation, and runtime security of the host node (e.g., SYS_ADMIN abuse).";
    u_en = "Prevents the dreaded 'container escape' (intrusion into the corporate host system) and deters misconfigurations or malicious use of cloud resources for cryptomining.";
  } else if (id.includes('cloud-sec') || id.includes('cspm') || id.includes('casb') || id.includes('cnapp')) {
    w_it = "Ecosistema di piattaforme dedicate (CNAPP, CSPM, CASB) adibito al controllo dell'infrastruttura Cloud (AWS, Azure, GCP) e delle applicazioni SaaS, integrando API esterne per validare l'identità, il network e i dati.";
    u_it = "Automatizza l'identificazione e la correzione di bucket S3 esposti, accessi IAM eccessivi e traffico anomalo. Indispensabile per arginare rischi nell'era del multicloud.";
    w_en = "Ecosystem of dedicated platforms (CNAPP, CSPM, CASB) designed to govern Cloud infrastructure (AWS, Azure, GCP) and SaaS applications, integrating external APIs to validate identity, networking, and data.";
    u_en = "Automates the identification and remediation of exposed S3 buckets, excessive IAM access, and anomalous traffic. Essential for curbing risks in the multicloud era.";
  } else if (id.includes('fed-id') || id.includes('iam') || id.includes('idm') || id.includes('iga')) {
    w_it = "Architettura di Identity & Access Management (e Governance correlata) progettata per disciplinare l'intero iter dell'identità digitale: assunzione (onboarding), modifiche e cessazione lavorativa (offboarding) attraverso regole di 'Least Privilege'.";
    u_it = "Neutralizza gli account silenti/orfani fantasma, previene minacce originate da insider malintenzionati ed elude tentativi di penetrazione derivati dal furto di credenziali.";
    w_en = "Identity & Access Management architecture (and related Governance) engineered to tightly govern the entire digital identity lifecycle: onboarding, changes, and offboarding through 'Least Privilege' rules.";
    u_en = "Neutralizes silent/orphan ghost accounts, prevents threats originating from malicious insiders, and evades penetration attempts derived from credential theft.";
  } else if (id.includes('mfa-sso')) {
    w_it = "Combinazione di Multi-Factor Authentication (esigere 2 o più fattori: password + app biometria/token) e Single Sign-On (login federato una sola volta per tutto l'ecosistema app).";
    u_it = "Annulla virtualmente l'impatto del phishing e del brute forcing delle password deboli, potenziando contemporaneamente un'intuitiva comodità per l'utenza finale.";
    w_en = "Combination of Multi-Factor Authentication (requiring 2+ factors: password + biometric/token app) and Single Sign-On (one-time federated login for the entire app ecosystem).";
    u_en = "Virtually nullifies the impact of phishing and weak password brute-forcing, while simultaneously boosting seamless convenience for end-users.";
  } else if (id.includes('pam')) {
    w_it = "Un framework tecnologico (Privileged Access Management) installato per segregare, registrare video o keystroke e revocare credenziali usate da figure tecniche di massimo profilo (Root, Domain Admin).";
    u_it = "Decisivo per stroncare ogni possibile 'Lateral Movement' (scalata). Anche se l'hacker entra nella rete base, non riuscirà a estrarre credenziali dominanti conservate sicure nel Vault PAM.";
    w_en = "A technological framework (Privileged Access Management) deployed to segregate, video/keystroke log, and revoke credentials utilized by peak-profile technical figures (Root, Domain Admin).";
    u_en = "Crucial to thwarting potential 'Lateral Movement' escalation. Even if a hacker breaches the base network, they cannot extract domain-dominating credentials safely vaulted inside PAM.";
  } else if (id.includes('rbac-abac') || id.includes('access-control')) {
    w_it = "Meccaniche di autorizzazione. Il Role-Based Access Control associa i permessi al titolo (HR, Dev), mentre il Attribute-Based applica regole dinamiche più complesse (es: HR + Da uffici Italia + Orari Lavorativi).";
    u_it = "Garantisce conformità microscopica su chi accede ai DB aziendali, evitando che permessi accumulati incorrettamente inneschino falle critiche nel corso degli anni.";
    w_en = "Authorization mechanics. Role-Based Access Control ties permissions to titles (HR, Dev), while Attribute-Based applies finer dynamic rules (e.g., HR + Originating from Italy + Working hours).";
    u_en = "Guarantees microscopic compliance spanning database access, preventing incorrectly amassed privileges from triggering critical flaws over the years.";
  } else if (id.includes('zero-trust')) {
    w_it = "Paradigma strategico estremo: la rete perimetrale interna non è più considerata intrinsecamente fidata. Tutte le transazioni, utenti, IP e pacchetti sono validati con crittografia esplicita ogni volta.";
    u_it = "È lo standard d'oro moderno per neutralizzare attori ransomware; confina istantaneamente l'intrusione al singolo host compromesso, sterilizzandolo dal resto della rete aziendale.";
    w_en = "Extreme strategic paradigm: the internal perimeter network is no longer inherently trusted. All transactions, users, IPs, and packets are explicitly cryptographically validated every single time.";
    u_en = "It serves as the modern gold standard against ransomware actors; it instantly contains unauthorized intrusions to the single compromised host, sterilizing it from the corporate network at large.";
  } else if (id.includes('firewalls') || id.includes('ids-ips') || id.includes('waf') || id.includes('network')) {
    w_it = "La suite fondamentale di ispezione dei pacchetti a strati profondi (L3-L7). Include Next-Gen Firewall per il traffico internet, WAF specifici per arginare iniezioni SQL su Web App e IPS per bloccare pattern malevoli.";
    u_it = "Filtra chirurgicamente il 'rumore' distruttivo della rete globale. Costituisce uno scudo preventivo invisibile a protezione di server web, API e dipendenti interni in navigazione.";
    w_en = "The core suite of deep packet inspection (L3-L7). Includes Next-Gen Firewalls for outbound traffic, specialized WAFs to curb SQL injections on Web Apps, and IPS to proactively drop malicious network patterns.";
    u_en = "Surgically filters the destructive 'noise' out of the global network. Builds an invisible pre-emptive shield guarding web servers, APIs, and internally browsing employees.";
  } else if (id.includes('ddos')) {
    w_it = "Hardware dedicato di rete o infrastrutture globali Edge (Distribuzioni CDN stile Cloudflare) architettati artificialmente per assorbire un'ondata gigantesca di traffico Internet fittizio prima che saturi i sistemi.";
    u_it = "Salvaguarda l'esistenza digitale dell'azienda (Availability). Previene che concorrenti o entità sovversive rendano invisibile il sito e i server vitali mandandoli in blocco e crash inaspettati.";
    w_en = "Dedicated network hardware or global Edge infrastructure (CDN distributions like Cloudflare) architected artificially to soak up gigantic waves of fictitious Internet traffic before they saturate internal systems.";
    u_en = "Safeguards the organization's digital availability. Prevents competitors or subversive entities from knocking vital corporate sites and servers into unexpected crashing states.";
  } else if (id.includes('patch-mgmt')) {
    w_it = "L'iter ingegnerizzato e cadenzato di rilevamento, collaudo (testing in pre-produzione) e immissione sul mercato interno degli aggiornamenti vitali (Patch) rilasciati dai vendor del software usato.";
    u_it = "Una macchina non patchata è una porta spalancata: questo dominio copre quelle porte sigillandole strutturalmente (applicando fix correttivi per difetti di Logica del codice originario CVE).";
    w_en = "The engineered and regimented workflow of discovering, pre-production testing, and internally rolling out critical software updates (Patches) dispatched by utilized software vendors.";
    u_en = "An unpatched machine is an open door: this domain securely seals those entries structurally (deploying corrective fixes targeting flawed source-code logic aka CVEs).";
  } else if (id.includes('baseline-config') || id.includes('secure-build')) {
    w_it = "Creazione della cosiddetta immagine d'oro (Golden Image/Baseline Hardening): un'architettura standard per i computer neo formattati dove Bluetooth non sicuro, porte SSH e macro USB esterne sono disabilitate di base.";
    u_it = "Garantisce che ogni singolo nuovo dispositivo porti intrinsecamente nel suo DNA una solida corazza tecnica pre-confezionata, resistendo efficacemente ai tentativi basilari da parte degli attaccanti (script-kiddies).";
    w_en = "Creation of the 'Golden Image' (Baseline Hardening): a standard deployment architecture for freshly formatted computers where insecure Bluetooth, SSH ports, and external USB macros are inherently disabled.";
    u_en = "Ensures every single novel device ships with robust operational armor genetically woven into its digital DNA, effectively repelling foundational attempts from attackers (script-kiddies).";
  } else if (id.includes('cryptography') || id.includes('key-secret') || id.includes('vaulting') || id.includes('hsm') || id.includes('cert-mgmt')) {
    w_it = "Ambito dedicato alla crittografia a chiave simmetrica/asimmetrica e alla conservazione estrema di materiale sensibile. Le chiavi primarie private in questi ambienti vengono generate in compartimenti Hardware ultra-specializzati (HSM).";
    u_it = "Garantisce matematicamente che, anche a fronte del peggiori furti fisici di dischi rigidi industriali, estrarre e leggere in chiaro l'immenso tesoro aziendale rubato o il database risulterà umanamente impossibile.";
    w_en = "Domain addressing symmetric/asymmetric cryptography and the extreme safekeeping of cryptographic material. Private primary keys in this ecosystem are generated entirely within hyper-specialized Hardware Security Modules (HSM).";
    u_en = "Mathematically guarantees that even enduring the most catastrophic physical theft of industrial server clusters, extracting readable plaintext out of the stolen corporate vault remains humanly impossible.";
  } else if (id.includes('ot-ics') || id.includes('scada')) {
    w_it = "Disegno di mitigazione del rischio ideato appositamente per le reti Operative Industriali (Robotica di catena, PLC o Sistemi Scada di dighe, ferrovie o centrali di produzione energetica idroelettrica); ambienti in cui latenza zero è imperativo vitale.";
    u_it = "Salva vite fisiche nel mondo reale prefigurando protezioni per le reti non conformi. Il blocco del software IT in banca danneggia il portafoglio: un blocco PLC su un impianto fonderia devasta l'ecosistema fisico della nazione.";
    w_en = "Risk mitigation framework engineered strictly for Industrial Operational Networks (Robotics lines, PLCs, or SCADA hubs managing dams, railways, and electrical power plants); realms prioritizing zero-latency lifelines.";
    u_en = "Preserves physical lives in the real world, guarding legacy non-compliant networks. IT software crashes cost banks dollars: PLC manipulation at a foundry plant physically devastates the nationwide grid ecosystem.";
  } else if (id.includes('hardware-sec') || id.includes('tpm')) {
    w_it = "Architettura hardware anti-interferenza integrabile fisicamente sulla scheda madre del computer come un microscopico caveau (chip TPM) deputato all'esecuzione indipendente crittografica. Sottosviluppo per un Boot Sicuro controllato dallo spegnimento all'accensione.";
    u_it = "Mette fuorigioco le classi di malware iper avanzate (Bootkit e Rootkit): un hacker da remoto pur possedendo le credenziali amministrative su Windows/Linux non riuscirà ad infettare logicamente moduli isolati sulla piastra.";
    w_en = "Anti-tamper hardware-level architecture physically integrated onto computer motherboards serving as a microscopic vault (TPM chip) dedicated solely to independent cryptographic executions. Core logic for End-to-End Secure Boot.";
    u_en = "Neutralizes hyper-advanced malware classes (Bootkits & Rootkits): even if remote hackers extract Windows/Linux administrative credentials, they utterly fail to logically infect sealed silicon layers.";
  } else if (id.includes('framework') || id.includes('cis') || id.includes('nist') || id.includes('iso') || id.includes('owasp') || id.includes('mitre') || id.includes('slsa')) {
    w_it = `Corpo accademico e industriale di metriche provate di maturità e checklist strategiche globalmente riconosciute dal mondo aziendale governativo (Cybersecurity Framework basati su analisi metodica del Mitre, del NIST statunitense o dello Standard ISO 27001).`;
    u_it = `Regala all'organizzazione metodologie cristalline pre-assemblate da ingegneri militari e analisti accademici che delineano come tracciare, implementare ed uditare oggettivamente un'adeguata ed infallibile architettura protettiva organica.`;
    w_en = `Academic and industrial corpus of proven maturity metrics and strategic compliance checklists globally mandated by corporate bodies (Cybersecurity Frameworks heavily anchored on Mitre analysis, US NIST directives, or standard ISO 27001).`;
    u_en = `Gifts organizations clear, pre-assembled blueprints crafted by military engineers and collegiate analysts outlining exactly how to trace, benchmark, and objectively audit infallible pervasive protective architecture arrays.`;
  } else if (id.includes('threat-hunting')) {
    w_it = "Dispositivo logico analitico basato sull'ipotesi. Indagini a tappeto effettuate manualmente in reti segrete aziendali alla spasmodica continua ricerca di anomalie nascoste e attaccanti APT silenti passati inosservati nonostante il muro dei sistemi automatici.";
    u_it = "Azzera la pericolosità dell'imprevedibile ed invisibile. Mentre i SOC normali attendono pacati che l'allarme SIEM suoni da solo prima di reagire, la task-force di Threat Hunting agisce come pattuglia preventiva in perlustrazione delle fogne informatiche dell'infrastruttura abbattendo significativamente il 'dwell-time'.";
    w_en = "Hypothesis-based logical analytical regimen. Sweeping, manual active investigations through classified corporate networks eagerly digging out concealed anomalies and stealthy sleeper APT attackers that seamlessly drifted unseen past the wall of automated sentries.";
    u_en = "Eliminates the danger of the invisible. While typical SOCs passively idle for SIEM alarms to shriek, the elite Threat Hunting task-force preemptively patrols the infrastructure's technical bowels significantly shaving off enemy 'dwell-time'.";
  } else if (id.includes('vuln-mgmt') || id.includes('vuln-scan') || id.includes('assets-inventory')) {
    w_it = "L'anello cruciale del risk reporting per quantificare dinamicamente le lacune architetturali (scanning) presenti all'interno del censimento digitale (inventory) informatico dell'intera compagnia per tracciarne il tracking sino alla dismissione definitiva del rischio medesimo.";
    u_it = "Si erge contro l'inevitabile logorio e la degenerazione di obsolescenza software. Se un hacker necessita che una porta del magazzino non sia oliata da mesi prima di scassinarla o farla crollare: questo sistema avvisa della necessità di rafforzarne gli stipiti ancor prima e sistematicamente in scala mondiale e geolocalizzata.";
    w_en = "The pivotal backbone of risk reporting constructed to dynamically quantify architectural gaps (scanning) currently lurking across the total footprint (inventory) of comprehensive digital company boundaries, ultimately monitoring tracking remediation closure.";
    u_en = "Champions defense against inevitable decay and software obsolescence drift. If criminal hackers secretly count on unoiled supply warehouse doors holding weak structural frames: this workflow issues prioritized systemic warnings mandating reinforcements to lock those doors across geolocated global scales beforehand.";
  } else if (id.includes('soar') || id.includes('siem') || id.includes('soc') || id.includes('detection')) {
    w_it = "Apparato militare reattivo di classe Enterprise: il SOC (Centro di Crisi Operativo della Sicurezza) usa Data Lakes a cui convergono TB di metadati (SIEM). Per evitare fatica cognitiva umana e risposte lente vengono instradati automaticamente i log da robot orchestratori (SOAR).";
    u_it = "Massimizza la probabilità astronomica che un minuscolo attacco silente avvenuto alle due e mezza del Lunedì di Ferragosto da una sperduta filiale secondaria del Messico venga catturato in millisecondi in tutto il pianeta e sradicato entro sessanta secondi successivi.";
    w_en = "Enterprise-class reactive military apparatus: the SOC (Security Operations Center hub) utilizes Data Lakes funneling Terabytes of metadata sets (SIEM). To avert dire human alert-fatigue and sluggish reactivity, robot orchestration dispatchers concurrently pivot flows autonomously (SOAR ecosystem).";
    u_en = "Maximizes the astronomical probability ensuring that a minuscule stealth attack triggering at 2 AM on a festive Monday emerging solely from an overlooked secondary Mexico-based subsidiary successfully captures global milliseconds attention and meets uncompromising eradication in under sixty ensuing seconds.";
  } else if (id.includes('incident') || id.includes('breach') || id.includes('containment') || id.includes('eradication')) {
    w_it = "Fase nevralgica letale di risposta all'impatto tecnico: un esteso corpus documentale tattico su come respirare durante violazione in atto orchestrato per guidare una squadra dall'individuazione alla tempestività del ripristino di business azzerando le radici fisiche del criminale.";
    u_it = "Aver formalmente approntato prima 'Incident Response' funge in azienda globale da ossigeno per chi sta per annegare durante l'apocalisse Cyber, frenando catastrofici effetti sismici collaterali altrimenti distruttivi del PIL per centinaia di milioni, sanzioni GDPR colossali derivate dal panico della C-Suite, gestendo mediaticamente l'orrendo Fallout informatico.";
    w_en = "Critical lethality response epicenter countering technical impact: an extensive tactical operational corpus illustrating breathing procedures while a hostile live-violation unfolds, systematically charting out a squad's roadmap scaling containment boundaries leading swiftly till utter business normalcy restoration uprooting digital parasite seeds.";
    u_en = "Having structurally curated preemptive 'Incident Response' embodies literal oxygen inside Fortune 500 arenas rapidly drowning under terrifying Cyber apocalypse. Curbs catastrophic seismic corporate collapse otherwise costing staggering hundreds of billions, averting devastating public-relations fallouts bleeding C-Suite market valuation during chaotic post-breach madness.";
  } else if (id.includes('team') || id.includes('bas')) {
    w_it = "Simulazione automatica avanzata o Wargames simulati d'èlite informatici: i Penetration Testers dell'In-house Team Hackerano senza limiti prestabiliti per individuare falle di spionaggio di alto profilo (Red) sfidando in duello asimmetrico le forze di contenimento interne e SOC di difesa attiva (Blue), supportati inoltre dall'addestramento cognitivo fuso nel mezzo (Purple).";
    u_it = "Funziona spietatamente evidenziando senza filtri l'amarissima e preziosa realtà scientifica oggettiva della conformità aziendale rispetto alle promesse astratte ed edulcorate dai grandi vendor hardware o delle dichiarazioni PowerPoint del board dei direttori prima del grande attacco.";
    w_en = "Honed elite cyber-warfare wargame emulations or advanced adversary automated AI software grids (BAS): Internal specialized hackers violently compromise unchained corporate thresholds tracking bleeding-tier espionage leaks (Red) clashing dramatically in asymmetrical battlefield duels opposing resident SOC defensive phalanxes (Blue) seamlessly meshed collectively leveraging profound dual-training optimization doctrines (Purple).";
    u_en = "Mercilessly acts outlining without any sugar-coated filters the bitter objectively vitalizing scientific reality representing precise tangible operational prowess compared drastically opposite to theoretical promises pushed routinely by major hardware security vendors or PowerPoint boardroom manifestos preceding crushing actual disaster dates.";
  } else if (id.includes('career') || id.includes('training') || id.includes('coaches') || id.includes('education') || id.includes('awareness')) {
    w_it = "Investimenti massicci pedagogici nella prima e vera immensa frontiera e punto di fallimento totale degli assiomi ingegneristici della Cybersecurity globale: il dipendente distratto e l'errata interpretazione psicologica dell'attacco mediante sofisticate Social Engineering via Phishing.";
    u_it = "Tramuta ineccepibilmente la catena ingegneristica difensiva aziendale, elevando il livello concettuale di ogni singolo e semplice individuo collegato da 'facile bersaglio primario' vulnerabile alle lusinghe dell'avidità, della curiosità perversa, ad inestimabile ultimo avamposto critico di resistenza e identificazione precoce degli operatori Hacker criminali.";
    w_en = "Vast sweeping pedagogical institutional investments funneling into the primary sprawling frontier representing total cataclysm inherent inside all global Cybersecurity engineering axioms: the distracted employee encountering devastatingly misguided psychological perceptions clashing blindly alongside extremely sophisticated Social Engineering via personalized Phishing methodologies.";
    u_en = "Immaculately transforms sweeping corporate shielding infrastructure paradigms by exponentially escalating every lowly connected individual's conceptual baseline spanning from 'immensely facile vulnerable priority targets' entranced by perverse greed or weaponized curiosity toward uniquely priceless ultimate vanguard defense nodes operating explicitly anticipating rapid identification mechanisms thwarting infiltrating cyber-hack adversaries.";
  } else if (id.includes('appsec') || id.includes('cicd') || id.includes('shift-left') || id.includes('ssdlc') || id.includes('sec-ux')) {
    w_it = "Filosofia radicale della Software Security Development Lifecycle (SSDLC). Anticipazione del check massiccio di vulnerabilità logicamente annidate inserendolo forzatamente lungo i binari iniziali di assemblaggio delle pipeline automatiche gestite dai developer prima che divenga esecutivo ed immodificabile 'Shift-Left' a destra.";
    u_it = "Eliminazione sistemica istantanea proattiva e non reattiva posticipata in sede d'Audit di bug SQL-Injection letali codificati in maniera accidentale dal reparto interno del DevOps riducendo l'escalation disumana vertiginosa del prezzo della correzione monetaria tardiva pretesa da un disastro finale occorso ad app lanciate su Cloud pubblico per miliardi di entrate dirette.";
    w_en = "Radical philosophy powering Secure Software Development Lifecycle pipelines (SSDLC). Rigorous anticipatory massive-scale auditing scans ferrying logically nested susceptibilities aggressively forward pushing them deeply forcefully inside introductory initial tracks binding code-automation assemblies navigated by primary developers prior to hardline staging compilation manifesting rightwards 'Shift-Left'.";
    u_en = "Proactively executing instantaneous systemic eradication protocols, decisively circumventing deferred belated post-Audit reactionary nightmares originating out of fatal encoded SQL-Injection bugs incidentally launched by internal DevOps battalions. Fundamentally reducing incredibly inhuman late financial correction toll-prices triggered invariably during catastrophic ultimate breakdowns plaguing globally vaulted public-Cloud live apps rendering massive billions in revenue pipelines completely stagnant.";
  } else if (id.includes('sast') || id.includes('iast') || id.includes('sca') || id.includes('sbom') || id.includes('scan') || id.includes('source-code')) {
    w_it = "Esami chirurgici chirurgici approfonditi in esecuzione statica dei listati primari (Applicazioni in chiaro, non ancora tradotte dalla macchina compiuta). Ispezione strutturale dell'immenso volume open-source di librerie importate dall'esterno tracciandole fin nel dettaglio cristallino su una documentazione minuziosa governamentale detta S.B.O.M (La ricetta informatica dei componenti applicativi mondiali software).";
    u_it = "L'appalto critico indispensabile del futuro. Esclude categoricamente ai complessi server che il semplice utente stia lanciando segretamente nel file testuale principale chiavi AWS Hard-Coded in bella vista per ogni curioso pirata di analizzare. Smaschera l'introduzione letale della Supply Chain (vedasi famigerata Log4Shell).";
    w_en = "Exacting surgical deep-level static execution inspections scrutinizing primary naked listings (Plaintext applications completely untranslated spanning target binaries). Methodically probing humongous structural open-source external imported architectural volumes systematically pinning individual minutiae onto meticulously drafted robust governmental documentations heralded universally identifying 'Software Bill of Materials' S.B.O.M (World-Scale Digital recipe indexing granular composite sub-structures).";
    u_en = "Vanguard indispensable critical enterprise future underwriting mechanisms. Categorically shutting away incredibly hazardous chances featuring simple engineers recklessly hard-coding devastating overt-text AWS Root keys openly blatantly bare enabling random curious seafaring cyber-brigands free reign. Powerfully tears down lethally infused global Supply Chain injections definitively (witnessing widely infamous global Log4Shell mass-penetrations universally crashing world economies).";
  } else if (id.includes('risk') || id.includes('erm') || id.includes('cyber-insurance') || id.includes('assessment')) {
    w_it = "Traduzione algebrica pura della complessità astratta dell'invisibile universo informatico convertendolo su fredda e inopinabile matrice in denaro per determinare oggettivamente il Ritorno sugli Investimenti CISO (ROI/ROSI) trasferendo economicamente a coperture assicurative le responsabilità d'Impatto estremo tramite analisi rigorose a più variabili quantificanti l'Esposizione Aziendale al catastrofico.";
    u_it = "Pietra di Rosetta obbligata e basilare d'Intesa per stringere bilanci al tavolo del Consiglio d'Amministrazione e Board Of Directors. Ai manager o investitori milionari non interessa intrinsecamente cosa diavolo debbano operare i nodi Kubernetes in Cluster: interessano profondamente bilanci trimestrali coperti d'argine milionario bloccando emorragie finanziarie derivate d'inestinguibile bancarotta per un Cryptolocker o sanzioni da privacy.";
    w_en = "Pure algebraic translation fundamentally collapsing profoundly abstract invisible IT universes channeling raw analytical quantification exclusively transforming theoretical matrices strictly into indisputable cold hard currency determining objectively transparent CISO Return on Investment milestones (ROI/ROSI) definitively projecting extreme impacts shifting liability economic fallouts smoothly transferring via rigid quantifiable cyber-insurance policies accurately measuring Corporate Catastrophic Exposure algorithms.";
    u_en = "Mandatory foundational Rosetta Stone orchestrating massive scale budgets negotiating heavily among fiercely guarded Board of Directors realms. Million-dollar investors routinely drastically eschew inherently pondering intricate depths dictating explicit technical Kubernetes sub-node networking nuances: strictly obsessing ferociously commanding sweeping multi-million quarterly fiscal barriers staunchly plugging catastrophic systemic fiscal hemorrhages caused solely enduring unextinguishable bank-busting cryptolocker ransomware blitzes heavily laced under towering staggering privacy regulatory monetary fines shattering existential public domains immediately forever closing operations.";
  } else if (id.includes('threat-intel') || id.includes('ti-') || id.includes('osint') || id.includes('darkweb')) {
    w_it = "Processo strutturale analitico tattico/operativo OSINT. Intercetta informazioni su vulnerabilità specifiche, hash-file o firme degli IP da canali sicuri statali (FBI, ENISA, CERT) al pari di esfiltrazioni minuziose in anonimato spiando gli inferi sotterranei di chat russe non tracciate o deep-dark-net e traffico web oscuro degli operatori RaaS (Ransomware as a Service) per determinare le tendenze del crimine.";
    u_it = "Fornisce chiaroveggenza al Chief Information Security Officer prima persino che il fatidico attacco sia mai partito. Sapendo i vettori d'azione malevolo usati nelle ore passate in Ucraina tramite file di estensione precisa .doc macro o server d'impatto C2 (Command and Control) russi, l'infrastruttura Italiana può corazzarsi con 48 ore di vitale anticipo azzerando probabilità d'ingresso alle minacce della settimana medesima.";
    w_en = "Tactical operational analytical structural OSINT workflows meticulously intercepting discrete deep vulnerabilities, distinct granular malicious file-hashes, precisely capturing targeting IP signatures channeling exclusively vetted federal pipelines (FBI, ENISA, CERT networks) equally matching deeply untraceable methodical deep-dark-net infiltration effectively spying stealthily traversing obscure unmonitored Russian chatter-hubs analyzing RaaS (Ransomware as a Service) syndicate global trend behaviors preemptively.";
    u_en = "Grants unparalleled sweeping clairvoyance strictly aiding massive-scale Chief Information Security Officer operational horizons significantly far preceding initial execution blast-off windows spanning actual fateful strikes. Cognizant of precisely specific malicious-vector blueprints extensively heavily weaponized merely hours previously targeting Ukrainian hubs distributing particular .doc macro payloads linked deeply tethered communicating Russian C2 (Command and Control) proxy-networks, directly enabling globally dispersed Western infrastructure immediate profound proactive 48-hour vital fortified head-starts decisively plummeting successful penetration entry-breach possibilities mirroring identical immediate weekly systemic threats completely entirely offline avoiding critical impact destruction domains drastically.";
  } else if (id.includes('governance') || id.includes('laws') || id.includes('gdpr') || id.includes('privacy') || id.includes('compliance')) {
    w_it = "Ecosistema mastodontico burocratico legale e architettonico in conformità ai massimi dettami legiferati a garanzia pubblica dello stato, per blindare e anonimizzare per DNA stesso dei codici digitali ogni traccia delle persone civili, sancendo norme inflessibili per i settori Finanziari/Bancari, sanitari ed Enti Governativi (PCI, HIPAA).";
    u_it = "Incutere metodicità esecutiva in seno profondo alla filosofia aziendale. Oltre a scongiurare punizioni di entità stratosferiche in multe multi-milionarie che sfaldano la fiducia storica internazionale, innalza per osmosi un livello protettivo d'intrinseca trasparenza elevatissimo per arginare le enormi sfide legali internazionali sui reati dei big-data corporativi.";
    w_en = "Gigantic bureaucratic legal spanning compliance-oriented architectural ecosystems mandated strictly adhering tightly mapping paramount state-legislated regulations safeguarding unconditionally anonymizing intrinsically embedded DNA source code shielding unequivocally individual civil civilian footprints forever, forcefully enacting radically inflexible monolithic operational policies profoundly governing vast Healthcare, stringent Federal Financial/Banking institutions and widespread sensitive Governmental arenas exclusively (spanning dense PCI, heavy HIPAA boundaries endlessly globally).";
    u_en = "Drastically imposing massive sweeping executive methodical philosophy directly striking profoundly deeply woven corporate psychological tapestries drastically far beyond simply aggressively dodging utterly stratospheric punitive monumental multi-million global scale monetary disciplinary fines capable alone fracturing shattering established foundational multi-century international marketplace historic trusts irrevocably, systematically effectively organically elevating an intrinsically pure exceedingly fortified protective transparent paradigm fundamentally staving off navigating complex monumental worldwide legal-corporate multi-national big-data conglomerate regulatory criminal battlefields flawlessly perfectly cleanly successfully unscathed entirely thoroughly operating globally transparent entities consistently robust permanently solid continuously advancing strictly securely always reliably.";
  } else {
    // Generico 
    w_it = `Rigorosa componente tecnico-operativa specificamente riguardante: ${label}. Strumento ingegneristico posizionato dai CISO globali in architetture su larga scala come tassello d'emergenza o di monitoraggio fondazionale nel frame metodologico della moderna infosec, allineata ai collaudati cardini concettuali accademici.`;
    u_it = `L'epicentro d'utilità si snoda garantendo in maniera trasparente mitigazione strutturata, controllo minuzioso visivo dei registri operativi ed espansiva e reattiva tolleranza zero verso le anomalie cyber scaturenti da vulnerabilità derivate da dinamiche correlate all'ambito ${label} limitandole nel profondo originario riducendole considerevolmente prima dell'attuazione criminale estesa.`;
    w_en = `Strict technical-operational component fundamentally focused encompassing: ${label}. High-end global rigorous engineering tool meticulously deployed architecturally anchoring emergency tracking systems or widespread foundational continuous monitoring tightly embedded into profound global baseline CISO framework operations perfectly synced modeling internationally proven academic Information Security conceptual bedrock pillars continually organically worldwide consistently rigorously.`;
    u_en = `Epicenter utility organically unfolding ensuring transparent pervasive methodical structural massive risk mitigation inherently delivering granular intricate sweeping visual operational log management alongside highly expansive zero-tolerance reactionary horizons precisely combating massive severe cyber anomalies sprouting continuously radiating profoundly stemming solely originating natively originating entirely closely spanning tightly enveloping ${label} specific operational workflows radically eliminating catastrophic criminal potential preemptively substantially mitigating overarching extreme destructive impact flawlessly seamlessly permanently totally thoroughly securely actively aggressively globally continuously resilient systematically inherently practically safely optimally purely successfully altogether entirely correctly properly efficiently securely.`;
  }

  return {whatItIsIt: w_it, whatItIsEn: w_en, utilityIt: u_it, utilityEn: u_en};
}

const descriptions = {};

for(let {id, label} of nodes) {
  let {whatItIsIt, whatItIsEn, utilityIt, utilityEn} = getDetailedText(id, label);

  descriptions[id] = {
    whatItIs: { it: whatItIsIt, en: whatItIsEn },
    utility: { it: utilityIt, en: utilityEn }
  };
}

const out = [];
out.push('export interface NodeDesc {');
out.push('  whatItIs: { it: string; en: string };');
out.push('  utility: { it: string; en: string };');
out.push('}');
out.push('');
out.push('export const nodeDescriptions: Record<string, NodeDesc> = ' + JSON.stringify(descriptions, null, 2) + ';');

fs.writeFileSync('./src/data/nodeDescriptions.ts', out.join('\n'));
console.log("nodeDescriptions.ts GENERATED WITH ENCYCLOPEDIC TEXTS");
